config/routes.rb
Honymous::Application.routes.draw do

  root to: "home#index"
  devise_for :users

  resources :profiles do
    resources :comments
  end

  match "manage" => 'profiles#manage'
  match "profile/comment/increment" => 'comments#increment'
  match "profile/comment/decrement" => 'comments#decrement'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user

  has_many :counters
  has_many :comments, :through => :counters

  attr_accessible :ip_address

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :profile

  has_many :counters, :dependent => :destroy
  has_many :addresses, :through => :counters

  accepts_nested_attributes_for :counters

  attr_accessible :author, :comment

  def count
    up = Counter.where( :comment_id => self.id, :direction => "up" ).length
    down = Counter.where( :comment_id => self.id, :direction => "down").length

    if up == 0
      "#{down} down"
    elsif down == 0
      "#{up} up"
    else
      "#{up} up, #{down} down"
    end
  end

  def count_sum
    up = Counter.where( :comment_id => self.id, :direction => "up" ).length
    down = Counter.where( :comment_id => self.id, :direction => "down").length
    up = up * 36
    down = (down * 42) * -1
    count = up + down
  end

end

app/models/counter.rb
class Counter < ActiveRecord::Base
  belongs_to :address
  belongs_to :comments

  accepts_nested_attributes_for :address

  attr_accessible :comment_id, :direction, :address_attributes

  # custom validation method
  validate :ip_has_vote?

  def ip_has_vote?
    if Counter.exists?( :comment_id => self.comment_id, :address_id => self.address_id )
      errors[:base] << "Hey Bro, You cant vote twice."
    end
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :comments

  attr_accessible :name, :one_liner, :description, :public_profile, :user_id
  validates_presence_of :name, :one_liner, :description

  scope :pp, where(:public_profile => true)

  def self.search(search)
    if search
      pp.find(:all, :conditions => ['name LIKE ?', "%#{search}%"] )
    else
      pp.find(:all)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  def has_profile?
    self.profile != nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @profile = Profile.find(params[:profile_id])
    @comment = @profile.comments.create( params[:comment] )
    if @comment.save
      redirect_to :back
    else
      flash[:error] = "Sorry Your profile was not saved"
    end
  end

  def increment
    new_counter("up")
  end

  def decrement
    new_counter("down")
  end

  def new_counter(direction)
    counter = Counter.new( :direction => direction, :comment_id => params[:id] )
    counter.address = Address.find_or_create_by_ip_address(
      :ip_address => request.env['HTTP_X_FORWARDED_FOR']
    )
    if counter.save
      redirect_to :back
    else
      flash[:error] = "Vote not saved, You can't vote twice"
      redirect_to :back
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @profile_count = Profile.all.length
    @search = Profile.search( params[:search] )
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy, :manage]

  def authenticate_user
    redirect_to :new_user_session_path unless current_user
  end

  def index
    @search = Profile.search(params[:search])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.create( params[:profile] )
    @profile.user = current_user
    if @profile.save
      flash[:notice] = "This is your profile"
      redirect_to profile_path(@profile.id)
    else
      flash[:error] = "Hey, Make sure Everything is filled out"
      render :new
    end
  end

  def show
    @profile = Profile.find(params[:id])
    @profile_comments = Comment.where( 'profile_id' => @profile )
    @sorted_profile_comments = @profile_comments.sort_by{ |comment| comment.count_sum }.reverse
  end

  def manage
    @user_profiles = Profile.where( 'user_id' => current_user )
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update_attributes(params[:profile])
      flash[:notice] = "This is your updated profile"
      redirect_to profile_path(@profile)
    else
      flah[:error] = "could not update profile"
      redirect_to edit_profile_path(@profile)
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    if @profile.destroy
      flash[:notice] = "Requested profile has been deleted"
      redirect_to :back
    else
      flah[:error] = "Could delete profile"
      redirect_to :back
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    default_url = "#{root_url}images/guest.png"
    gravatar_id = Digest::MD5.hexdigest(user.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=180&d=mm"
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<div class="row">
   <div class="span8 offset4">
    <h1>
      Honymous
    </h1>
    <p class="lead">
      Honest and Anonymous comments
    </p>
    <%= render :partial => "profiles/search" %>
  </div>
</div>
<div class="row">
  <div class="span4">
    <h3>
      What is Honymous?
    </h3>
    <p>
      This is a mini social network of sorts. A place where You, a user can come and make a profile page to encourage feedback from your peers. You can ask for specific questions that you want answered, or you can cast a wide net for what you might find helpful. Your peers can then pop on anonymously and respond. What they may say could brighten up your day, or bring some perspective to the conversation.
    </p>
  </div>
  <div class="span4">
    <h3>
       What is this voting?
    </h3>
    <p>
      A voting system is in place to help moderate the anonymous comments. It allows each person to vote once on a comment that they feel strongly about. If in the event that "Mary" just got a hair cut and her ex-boyfriend chimes in with something mean, all of her friends can vote down the comment and it will be discredited by the community around Mary.
    </p>
  </div>
  <div class="span4">
    <h3>
      Who made this?
    </h3>
    <p>
      It was me, Christopher Fryman. I am Jr Developer graduating from the <a href="http://www.nashvillesoftwareschool.com/">Nashville Software School</a>. The goal of this project was to showcase the skills that I learned through the six-month boot camp. It was a project that I thought would be fun and that people might like to play around with.
    </p>
    <p>
      If you like it and want to hire me I am available for the time being. Take a look at my <a href="http://www.github.com/farfromguam">Github repository</a>, and my <a href="http://www.linkedin.com/in/cfryman">linkedin profile</a>. Lets talk.
    </p>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>

<%= link_to "Honymous", root_path, :class => 'brand' %>

<div class="nav-collapse navbar-responsive-collapse collapse" >
  <ul class="nav pull-right">
    <% if user_signed_in? %>

      <li>
        <%= link_to current_user.email, edit_user_registration_path %>
      </li>

      <% if current_user.has_profile? %>
        <li>
          <%= link_to "Manage your Profiles", manage_path %>
        </li>
      <% else %>
        <li>
          <%= link_to "Create a profile", new_profile_path %>
        </li>
      <% end %>

    <% else %>
      <li>
        <%= link_to('Sign up', new_user_registration_path)  %>
      </li>
    <% end %>

    <% if user_signed_in? %>
      <li>
        <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
      </li>
    <% else %>
      <li>
        <%= link_to('Login', new_user_session_path)  %>
      </li>
    <% end %>

  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Honymous" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile, :html => { :class => 'form-horizontal' }) do |f| %>
  <label>
    <%= f.label :name, "Your Name" %>
  </label>
  <div class="input">
  <%= f.text_field :name, :class => "input-xlarge" %>
  </div>

  <label>
    <%= f.label :one_liner, "A one-liner to help people find you" %>
  </label>
  <div class="input">
    <%= f.text_field :one_liner, :class => "input-xlarge"  %>
  </div>

  <label>
    <%= f.label :description, "What are you looking for feedback on?" %>
  </label>
  <div class="input">
    <%= f.text_area :description, :class => "input-xlarge", :rows => 6 %>
  </div>

  <div class="input">
    <%= f.input_field :public_profile, as: :boolean, inline_label: "Make my profile public" %>
  </div>

  <div class="form-button">
    <%= f.submit "Submit", :class => "btn" %>
  </div>
<% end %>

app/views/profiles/_search.html.erb
<%= simple_form_for :search, { :url => profiles_path, :method => 'get' } do |f| %>
  <div class="input-append">
    <%= text_field_tag :search, params[:search], :class => "input-medium" %>
    <%= submit_tag "Search", :name => nil, :class => "btn" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit your Profile</h1>

<%= render :partial => "form" %>

app/views/profiles/index.html.erb
<h1>Search results</h1>

<%= render :partial => "profiles/search" %>

<p>
<% if @search.length == 0 %>
  Your search returned no results.<br>
  Remember private profiles dont show up in searches
<% else %>
  <% @search.each do |profile| %>
    <%= link_to(profile.name, profile_path(profile.id)) %> - <%= profile.one_liner %><br>
  <% end %>
<% end %>
</p>

app/views/profiles/manage.html.erb
<div class="row">
  <div class="span3 text-right hidden-phone">
    <p>
      <%= image_tag avatar_url(current_user.email), :class => "img-polaroid" %>
    </p>
    <p>
      <a href="http://www.gravatar.com" target="_blank">Your Gravatar Image</a>
    </p>
    <p>
      <%= link_to "Edit Login Settings", edit_user_registration_path %>
    </p>
  </div>
  <div class="span5">
  <div class="span3 visible-phone">
    <p>
      <%= image_tag avatar_url(current_user.email), :class => "img-polaroid" %>
    </p>
    <p>
      <a href="http://www.gravatar.com" target="_blank">Your Gravatar Image</a>
    </p>
    <p>
      <%= link_to "Edit Login Settings", edit_user_registration_path %>
    </p>
  </div>
  <div class="span5">

    <h1>Your profiles</h1>

    <% @user_profiles.each do |profile| %>
      <div class="well well-small">
        <h4>
          <%= profile.name %>
        </h4>
        <p>
          <%= profile.one_liner %>
        </p>
        <% if !profile.public_profile %>
          <p>
            This profile is private. To share, email this URL:<br>
            <%= profile_url(profile) %>
          </p>
        <% end %>
        <p>
          <%= link_to "Visit", profile_url(profile), :class => "btn btn-success"  %>
          <%= link_to "Edit", edit_profile_url(profile), :class => "btn btn-warning" %>
          <%= link_to "Delete", profile_url(profile), :method => :delete, :class => "btn btn-danger" %>
        </p>
      </div>
    <% end %>

    <%= link_to "New Profile", new_profile_path, :class => "btn" %>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render :partial => "form" %>

app/views/profiles/show.html.erb
<div class="row">
  <div class="span3 text-right hidden-phone">
    <%= image_tag avatar_url(@profile.user.email), :class => "img-polaroid" %>
  </div>
  <div class="span3 visible-phone">
    <%= image_tag avatar_url(@profile.user.email), :class => "img-polaroid" %>
  </div>
  <div class="span5">
    <h1>
      <%= @profile.name %>
    </h1>
    <h4>
      <%= @profile.one_liner %>
    </h4>
    <p>
      <%= @profile.description %><br><br>
    </p>

    <% if @sorted_profile_comments.length > 0 %>
      <h4>What people are saying about <%= @profile.name %>:</h4>
      <% @sorted_profile_comments.each do |comment| %>
        <div class="well well-small">
          <p>
            <%= comment.comment %><br>
          </p>
            <% if comment.count_sum >= 0 %>
              <i class="icon-star"></i> <%= comment.count_sum %> |
            <% else %>
              <i class="icon-warning-sign"></i> <%= comment.count_sum %> |
            <% end %>
            <%= link_to "Vote Up", :controller => "comments", :action => "increment", :id => comment.id %> |
            <%= link_to "Vote Down", :controller => "comments", :action => "decrement", :id => comment.id %>
        </div>
      <% end %>
    <% end %>

    <h4>Say something:</h4>
    <%= form_for [@profile, @profile.comments.new] do |f| %>
      <label>
        <%= f.label :comment, "Your Comments:" %>
      <label>
      <%= f.text_area :comment, :class => "input-xlarge", :rows => 5 %><br>
      <%= f.submit "Submit", :class => "btn" %>
    <% end %>
  </div>
</div>